from day1111.bst import *

t=BST()
t.put(90,'수박')
t.put(80, '배')
t.put(70, '멜론')
t.put(50, '라임')
t.put(60, '망고')
t.put(20,'체리')
t.put(30, '포도')
t.put(35, '오렌지')
t.put(10, '귤')
t.put(15,'바나나')
t.put(45,'레몬')
t.put(40,'키위')
t.inorder(t.root)
print()
t.delete(40)
t.inorder(t.root)
#찾기기능
print()
print(t.get(80))
min=t.min()
print(min.key, min.value)